### PR TITLE
refactor to dillonkearns/elm-graphql

### LINKED ISSUE #1: Refactor to use @dillonkearns elm-graphql
https://github.com/dillonkearns/elm-graphql

We are all on board on the idea of sharing the schemas and types between the frontend and the backend 🎉 

But for some reason I could not easily make this library to work with our `schema.graphql`, need to investigate more! 🤔

### PR DESCRIPTION
**Pull request by vladimirlogachev**
Fixes #1

### CODE REVIEW

**Comment by vladimirlogachev** [comment]
Why delete package.lock?

**Comment by kutyel** [comment]
Sorry, It adds undue noise to the PR, in any case I'll take a `yarn.lock` but wanted to be able to do everything with just an `elm.json` if possible to make the example as minimal as possible. I'll try this out and review the rest of the PR on Monday, thanks for your great work! 🙌

**Comment by vladimirlogachev** [comment]
Leaving `elm-graphql` and `elm-app` global dependencies makes an example unstable.
Removing `package.lock` does not make it very unstable, but it certainly does.
I'm on the same page with you about `elm.json`, but we need 2 cli tools, which can not be implemented in pure elm.
Also to implement subscriptions we need to write some JavaScript code.

Alternatives to npm: 
- docker + globally installed npm packages with their versions fixes in dockerfile (in fact, same thing as removing package.lock - transitive dependencies may upgrade and break the whole thing one day). This adds docker to our equation.
- nix. This adds nix. Maybe it's the best option, but it will scare some of our users.

`yarn.lock` adds yarn to this project without removing dependency on npm, not sure if it will be a good decision.

Summary: I do think that accepting some noise of `package-lock.json` is the lowest price of making an example stable.

**Comment by kutyel** [comment]
Makes sense, I'd love to have an example with **Nix** if it is possible (although that can go in a separate PR if you want). 🙏 
Always wanted to use Nix with Elm but haven't been able to find time nor the resources, so maybe this repo could serve as a good example to the community as well! 🙌

**Comment by kutyel** [comment]
For me particularly I struggle with having lots of notifications from GitHub when lock files are committed, because of _"security issues"_ that are not important for example repos, etc, etc...

**Comment by vladimirlogachev** [comment]
Vulnerabilities come from the state of the JS ecosystem. We can mark each notification as an irrelevant, and notification will go away. Not committing lock files makes life harder when a year passes and someone tries to compile the example. Ideally, we should also fix the node.js version, but at least it can be deduced from commit dates. But the correct lockfile is better be provided than not. Consider putting it back. At least it guarantees that people will use the same versions as we do, which is undecidable without lock.

Nix - yeah, I plan to do so, will make another PR when I figure out all the things.

**Review by kutyel — APPROVED** [review]
It works great, thanks @VladimirLogachev!

However, it does not benefit from the regex author name queries... simply returns everything all the time, any idea to improve this on another PR? 🤔

**Comment by VladimirLogachev** [comment]
Sure. First I clarify if the behavior of the library server is correct.

**Pull request merged**
