### PR TITLE
Add subscriptions example

### PR DESCRIPTION
**Pull request by vladimirlogachev**
Everything is working at Elm side, but blocked by https://github.com/higherkindness/mu-haskell/issues/259

### CODE REVIEW

**Comment by vladimirlogachev** [comment]
Also, I refactored `init` to record syntax because it's not just boilerplate or "glue code". `init` tells the reader about where the app state was at the beginning, and constructor argument syntax makes it much harder to understand.

Just imagine that you are reading the code for the first time, and I hope you will agree with it.

**Comment by serras** [comment]
It definitely reads better, and it's more beginner-friendly. Thanks!

**Comment by vladimirlogachev** [comment]
@kutyel , I did not update a screenshot, because your screenshotting tool works much better than mine))

**Comment by vladimirlogachev** [comment]
Testing it live may be difficult because of https://github.com/higherkindness/mu-haskell/issues/262.
However, Elm and JS code in this example works fine and I think of it as ready.

**Comment by kutyel** [comment]
Awesome, thanks so much for your work @VladimirLogachev! I'll review this as soon as possible 😉 
My screenshotting tool is just `cmd + shft + 4` on a Mac, choosing the window with toolbars option! 📸

**Comment by vladimirlogachev** [comment]
Thank you so much! I promise to use `cmd + shift + 4 ` as soon as *Apple MacBook Air on M1* sales will start in Russia _(which, unfortunately, is far from today)_

**Review by kutyel — APPROVED** [review]
LGTM, thanks @VladimirLogachev! 🚀

**Pull request merged**
