### PR TITLE
Refactor an app, add mutations

### PR DESCRIPTION
**Pull request by vladimirlogachev**
This Elm example aims to demonstrate how to implement both frontend and backend in a schema-first, typesafe, and functional way.

So my goal for this example is not only to add mutations and subscriptions but also to make the app so nice that it will be pleasant to refer to. That is why I considered it a good idea to apply some polish without adding unnecessary complexity (I understand that it's also very important for this example).

Changed: 
- Factor out search page from main
- Change styles (adjust it to be similar to the mu-haskell page)
- Get rid of combined tasks, instead combine selections in one query
- Move search-related graphql functions to the `Search` module
- Add Editor page
- Add mutations for adding a book with either a new or an existing Author
- Handle states in Editor: loading, success, failure. Redirect to filled search on success, to empty search on cancel.
- Implement UI for selecting an existing author
- Improved docs and comments

### CODE REVIEW

**Comment by vladimirlogachev** [comment]
Makes sense to wait for https://github.com/higherkindness/mu-haskell/pull/248 and only then merge, because now it will assume the updated schema.

(And, of course, we should re-run `Elm CI` check)

**Comment by kutyel** [comment]
> Makes sense to wait for [higherkindness/mu-haskell#248](https://github.com/higherkindness/mu-haskell/pull/248) and only then merge, because now it will assume the updated schema.
> 
> (And, of course, we should re-run `Elm CI` check)

Makes sense to wait before reviewing this, I just merged the other PR 😉  Thanks for your work! 🙌🏻

**Review by kutyel — APPROVED** [review]
Looks great! Although I don't know if you've seen this talk https://www.youtube.com/watch?v=XpDsk374LDE 😉

**Comment by vladimirlogachev** [comment]
Of course, I did! It's one of my favorite talks.
That's why tasks have moved closer to pages.
And that's why I've separated "types that look kinda same". Because they're not.
And that's why I've extracted only reusable functions and removed generic view for RemoteData.
: )

**Comment by kutyel** [comment]
Great! I also felt like moving everything to its own file at the beginning, but that talk helped me to understand that it's ok to have files with 400+ LOC, now I feel better while doing Elm and try to split files into modules when it is absolutely necessary 😉

**Comment by vladimirlogachev** [comment]
I also keep in mind the single responsibility principle (which is about architecture reasonability but not about safe/unsafe and pure/impure). And I also like the code to deal with either abstract or concrete details, but not mixing up big and tiny details. But that talk makes perfect sense, anyway.

**Pull request merged**
