### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by vladimirlogachev**
- Get rid of yarn
- Install elm-graphql CLI as a local dependency
- Update elm dependencies
- Don't ignore the generated elm code anymore
  _I have practically used elm code generation a lot, and my experience tells me that ignoring the generated code is a bad idea because it makes it hard to inspect the changes in the generated code when changing Haskell code or updating dependencies._

### CODE REVIEW

**Comment by vladimirlogachev** [comment]
The cachix-related CI failure is unrelated to my changes.
@serras Is there a chance that you could help me with it?

**Comment by serras** [comment]
@VladimirLogachev could you try to update the Cachix action to `v12` in the workflow?

**Comment by vladimirlogachev** [comment]
@serras Didn't help

**Comment by sandydoo** [comment]
@VladimirLogachev, the actual issue is with the Nix installer, not Cachix. Upgrading to `v20` should resolve the issue 🙂 

```yaml
- uses: cachix/install-nix-action@v20
```

**Comment by vladimirlogachev** [comment]
@sandydoo  Thank you, it worked!

**Review by serras — APPROVED** [review]

**Pull request merged**
